[project]
name = "cast-snap"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "black>=25.9.0",
    "boto3>=1.40.67",
    "parse-args>=2.0.0",
    "python-dotenv>=1.2.1",
]
